project:
  type: website
  output-dir: _site

website:
  title: "Søren D. Petersen"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - presentations.qmd
      - yield_predictor.qmd
      - about.qmd
    right:
      - icon: fa-github
        href: https://github.com/sorpet
        text: "<i class='fab fa-github'></i> GitHub"
      - icon: fa-linkedin
        href: https://www.linkedin.com/in/soerendpetersen  # Replace with your LinkedIn profile URL
        text: "LinkedIn"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    fontawesome: true

editor: visual

execute:
  freeze: auto
