project:
  type: website
  output-dir: _site
  resources:
    - "cv/**"

website:
  title: "Søren D. Petersen"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: Examples of digital tools
        menu:
          - href: yield_predictor.qmd
            text: Yield predictor
          - href: biofertilizer.qmd
            text: Biofertilizer network
          - href: mycoid.qmd
            text: Sequence Chromatogram Viewer

      - text: CV
        href: cv/main.html
      # - about.qmd

    right:
      - icon: fa-github
        href: https://github.com/sorpet
        text: "<i class='fab fa-github'></i> GitHub"
      - icon: fa-linkedin
        href: https://www.linkedin.com/in/soerendpetersen  # Replace with your LinkedIn profile URL
        text: "LinkedIn"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    fontawesome: true

editor: visual

execute:
  freeze: auto
