project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "cv/index.qmd"

website:
  title: "Søren D. Petersen"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: Examples of digital tools
        menu:
          - href: yield_predictor.qmd
            text: Yield predictor
          - href: biofertilizer.qmd
            text: Biofertilizer network
          - href: mycoid.qmd
            text: Sequence Chromatogram Viewer

      - text: CV
        href: cv/index.qmd
      # - about.qmd

    right:
      - icon: github
        href: https://github.com/sorpet
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/soerendpetersen
        aria-label: LinkedIn

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    fontawesome: true
    include-after-body: site-scripts.html

editor: visual

execute:
  freeze: auto
